name: CI/CD - Build, Push e Atualiza Manifests

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: guilherme420/hello-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push da imagem
      id: build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Configurar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clonar repositório de manifests
      run: |
        git clone git@github.com:guilourenz01/hello-manifests.git manifests

    - name: Atualizar deployment.yaml com nova tag
      run: |
        cd manifests
        NEW_IMAGE="${{ env.IMAGE_NAME }}:${{ github.sha }}"
        echo "Atualizando imagem para: ${NEW_IMAGE}"
        sed -i "s|image: .*|image: ${NEW_IMAGE}|g" deployment.yaml
        git config user.email "actions@github.com"
        git config user.name "github-actions"
        git add deployment.yaml
        git commit -m "ci: atualiza imagem para ${NEW_IMAGE}" || echo "Nenhuma mudança para commitar"
        git pull --rebase origin main || true
        git push origin main
